### ISSUE TITLE
1.3 CAP on EKS

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/doc-cap#218]
Updated instructions:
https://github.com/SUSE/scf/wiki/Deployment-on-Amazon-EKS#deployment

Changes:
the following roles need to have SYS_RESOURCE capabilities:
cc_uploader
diego_ssh
diego_brain
diego_api
nats
routing_api

```
sizing:
  cc_uploader:
    capabilities: ["SYS_RESOURCE"]
  nats:
    capabilities: ["SYS_RESOURCE"]
  routing_api:
    capabilities: ["SYS_RESOURCE"]
  router:
    capabilities: ["SYS_RESOURCE"]
  diego_ssh:
    capabilities: ["SYS_RESOURCE"]
  diego_brain:
    capabilities: ["SYS_RESOURCE"]
  diego_api:
    capabilities: ["SYS_RESOURCE"]
```
