### ISSUE TITLE
Update capabilities config and PSP for CaaSP 3 with updates applied

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#225]
CaaSP 3 with upgrades, dependent on the upgrade version and version of Kubernetes used, will now require setting the capabilities.

```
sizing:
  cc_uploader:
    capabilities: ["SYS_RESOURCE"]
  nats:
    capabilities: ["SYS_RESOURCE"]
  routing_api:
    capabilities: ["SYS_RESOURCE"]
  router:
    capabilities: ["SYS_RESOURCE"]
  diego_brain:
    capabilities: ["SYS_RESOURCE"]
  diego_api:
    capabilities: ["SYS_RESOURCE"]
  diego_ssh:
    capabilities: ["SYS_RESOURCE"]
```

`kube.psp.nonprivileged` (and `kube.psp.privileged`) also need to be set in config yaml to specify psp being used.

```
kube:
  psp:
    nonprivileged: ...
    privileged: ...
```

`allowedCapabilities: ['SYS_RESOURCE']` will then need to be specified in the psp yaml file

Otherwise the following will be encountered and some pods will not be available

```
  Warning  FailedCreate  49m (x170 over 125m)  statefulset-controller  create Pod router-0 in 
StatefulSet router failed error: pods "router-0" is forbidden: unable to validate against any pod security 
policy: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not 
allowed spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing 
privilege escalation for containers is not allowed]
  Warning  FailedCreate  4m45s (x86 over 45m)  statefulset-controller  create Pod router-0 in 
StatefulSet router failed error: pods "router-0" is forbidden: unable to validate against any pod security 
policy: [capabilities.add: Invalid value: "SYS_RESOURCE": capability may not be added 
spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege 
escalation for containers is not allowed]
```
