### ISSUE TITLE
Recommend setting a default storageclass

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#248]
Docs are a little thin on storage classes and how to set them up. Understandable because this is really a Kubernetes-level prerequisite. That said, we should recommend that operators create at least one storage class which is flagged as default, because Minibroker (and possibly other optional charts) require this. 

This is from my nfs-client yaml:
```
storageClass:
  create: true
  defaultClass: true
  name: nfs-client
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: false
```
