### ISSUE TITLE
[doc] 5.5.1  Install Stratos Metrics with Helm

### ISSUE THREAD

**Issue by greygoo** [SUSE/doc-cap#398]
5.5.1  Install Stratos Metrics with Helm

http://docserv.nue.suse.com/documents/CAP_1/cap-guides/html/cha.cap.install-stratos.html#sec.cap.stratos-metrics-install

While testing this I with cap 1.4.0 RC2 I discovered that in order to have the metrics tabs to appear in the Stratos UI an additional entry is needed in the  `stratos-metrics-values.yaml` file.

This is the stratos-metric-values.yaml file from the current documentaion:

```
kubernetes:
  authEndpoint: kube_server_address.example.com
prometheus:
  kubeStateMetrics:
    enabled: true
nginx:
  username: username
  password: password
useLb: true
```

This is the stratos-metrics-values.conf file with the additional DOPPLER entry required for 1.4.0 RC2:

```
env:
    DOPPLER_PORT: 443
kubernetes:
  authEndpoint: kube_server_address.example.com
prometheus:
  kubeStateMetrics:
    enabled: true
nginx:
  username: username
  password: password
useLb: true
```
