### ISSUE TITLE
[doc] 6.6.1  Install Stratos Metrics with Helm

### ISSUE THREAD

**Issue by dsohk** [SUSE/doc-cap#606]
6.6.1  Install Stratos Metrics with Helm

https://documentation.suse.com/suse-cap/1.5/html/cap-guides/cha-cap-install-stratos.html#sec-cap-stratos-metrics-install

The sample `stratos-metrics-values.yaml` file listed deprecated key. It should be `kubernetes.apiEndpoint`, not `kubernetes.authEndpoint` with SUSE CAP 1.5 release.

**Comment by dsohk** [comment]
A working example would be like below:

```
---
kubernetes:
  authEndpoint: https://api.caasp4demo.com
prometheus:
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true
  server:
    persistentVolume:
      storageClass: gp2scoped
metrics:
  username: mymetrics
  password: mysecret
services:
  loadbalanced: true
```
