### ISSUE TITLE
Example HA Configuration - Wrong UAA HA sizing parameters

### ISSUE THREAD

**Issue by paraenggu** [SUSE/doc-cap#85]
The current [UAA HA sizing parameters](https://github.com/SUSE/doc-cap/blob/e421822d693d36128382e61a85d9f5e6c2c7b291/xml/cap_depl_install_production.xml#L931-L963) for the `uaa-sizing.yaml` seem to be wrong and were probably copy and pasted from the [SCF sizings](https://github.com/SUSE/doc-cap/blob/e421822d693d36128382e61a85d9f5e6c2c7b291/xml/cap_depl_install_production.xml#L969-L997).

The `uaa-sizing.yaml` yaml file should probably look similar to:
```yaml
sizing:
  mysql:
    count: 3
  mysql_proxy:
    count: 3
  uaa:
    count: 3
```
However, I'm unaware of the actual recommended HA sizing parameters.
