### ISSUE TITLE
Test Storage Class Doc Error

### ISSUE THREAD

**Issue by bdekany** [SUSE/doc-cap#87]
Hi,

There is an indentation error in the test-storage-class.yaml example.
`StorageClassName` is not a member of `requests` but `spec` 

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sc-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      storageClassName: persistent
````
Should be:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sc-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
````

2.3  Test Storage Class

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.teststorageclass-prod
