### ISSUE TITLE
Change default EKS storageclass to use EFS, not GP2

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#918]
Based on some recent observations on EKS deployments with CAP 2, we need to encourage admins to deploy with EFS as the backing storage. We've mentioned GP2 in the documentation before but there is a limit to how many PVCs can be joined to that storage unit. It also cannot span multiple zones in the way that EFS does, though we may have to be mindful that EFS has its own limits on write operations per second.

@troytop can provide more details.

**Comment by jandubois** [comment]
Isn't there some issue with `diego-cell` and EFS? Because garden tries to allocate all available disk space, minus some reserved amount, like 15GB, to the grootfs, and then there is a problem allocating a sparse file of that size?

I have some notes from Andrew/Vlad that you can work around this with something like this:

```
properties:
  diego-cell:
    rep:
      diego:
        executor:
          disk_capacity_mb: 40960
    garden:
      grootfs:
        reserved_space_for_other_jobs_in_mb: 8796051063807
```

But that feels more like a hack than a solution, so I don't think this should go into the docs as the recommended configuration.
