### ISSUE TITLE
Instructions to connect to an external database

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#930]
The below is a reference config tested/provided by Satadru.

```
features:
    embedded_database:
        enabled: false
    external_database:
        emabled: true
        require_ssl: false
        type: mysql
        host: EXAMPLE_HOSTNAME
        port: 3306
        databases:
          uaa:
            name: uaa
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          cc:
            name: cloud_controller
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          bbs:
            name: diego
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          routing_api:
            name: routing-api
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          policy_server:
            name: network_policy
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          silk_controller:
            name: network_connectivity
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          locket:
            name: locket
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
          credhub:
            name: credhub
            password: EXAMPLE_PASSWORD
            username: EXAMPLE_ADMIN_USER
```

@btat or @KucharczykL to do test deployments, one for MySQL/MariaDB ~~and one for PostgreSQL~~, and write up instructions based on the that.

Configurations to test to be confirmed. For example,
- SSL enabled (may require extra configs)
- Which backends should be tested. E.g. AWS RDS MariaDB/MySQL ~~, PostgreSQL~~ etc.
