### ISSUE TITLE
log-cache workaround for docs and release notes

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#975]
There's a problem with allocating memory within log-cache that's detailed in https://github.com/cloudfoundry/gosigar/issues/48

Until that's addressed, we need to use node affinity to tie log-cache to nodes of a uniform size, and then declaring the cache percentage based on that number. log-cache also needs to be non-HA.

Based on this bit of YAML, 3% is enough to contain this for now:

```
properties:
  log-cache:
    log-cache:
      memory_limit_percent: 3

operations:
  inline:
  - type: replace
    path: /instance_groups/name=log-cache/env?/bosh/agent/settings/affinity
    value:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - caasp4-worker-2
```

Quoting:
I've confirmed that the pod has the requested affinity setting, and that the `memory_limit_percent `is passed through to the log-cache job.

Note that this changes the log-cache pod, as the job is no longer co-located with doppler. It is also not possible to scale up the log-cache instance group by setting `sizing.log-cache.instances`; that variable is not used by the chart.

[...]

The `memory_limit_percent` property should limit the total cache size to 3% of the total node memory, being 960 MiB in the case of the 32 GiB nodes of the sandbox.

`config.memory.limits` must be enabled so that the helm chart does not ignore the limits specified for individual pods. Setting the doppler limit to 2000 MiB then allows the log-cache process to leak an additional 1 GiB before it gets killed by the OOM killer.

The nodeAffinity rule was included mostly for the benefit of the BIT configuration, which uses a range of node sizes, so we need to be able to limit doppler/log-cache instances to a group of nodes all using the same memory size.
